name: Daily Commit
on:
  schedule:
    # Runs at 12:00 UTC every day
    - cron: '0 12 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with email 23f2004665@ds.study.iitm.ac.in
        uses: actions/checkout@v4
        
      - name: Create commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          date > daily-commit.txt
          git add daily-commit.txt
          git commit -m "Daily automated commit"
          git push